# Generated by Django 3.0.4 on 2020-03-21 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Article_aa',
        ),
    ]
