# Generated by Django 3.0.4 on 2020-03-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200321_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_aa',
            name='pub_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article_aa',
            name='content',
            field=models.TextField(default='content', max_length=64),
        ),
    ]
